language: java
jdk:
- oraclejdk8
script: mvn -X -DPACT_BROKER_USERNAME=$PACT_BROKER_USERNAME -DPACT_BROKER_PASSWORD=$PACT_BROKER_PASSWORD -DPACT_BROKER_HOST=$PACT_BROKER_HOST -DPACT_BROKER_TARGET_FOLDER=$PACT_BROKER_TARGET_FOLDER  clean install
 
 
